### ISSUE TITLE
Package overview

### ISSUE THREAD

**Issue by cytec** [SynoCommunity/spkrepo#1]
@Diaoul maybe you'll should delete this: https://github.com/Diaoul/spkrepo/blob/master/spkrepo/static/css/spkrepo.css#L51-L53 so the packages get a little bit more spacing at the bottom :)

**Comment by Diaoul** [comment]
I'll rework spkrepo so it only fill the backend job with no frontend except for the admin part.
As for SynoCommunity's website I'll make a new one with angularjs that queries the API.

CC @Piwilabruti
