### ISSUE TITLE
Upload keeps failing 

### ISSUE THREAD

**Issue by Safihre** [SynoCommunity/spkrepo#103]
I have tried a couple of times, but this 1 upload for evansport keeps failing. Is there anything wrong server side?
https://github.com/Safihre/spksrc/actions/runs/4916395862

**Comment by hgy59** [comment]
AFAICS sabnzbd v4.0.1-61 for evensport-7.1 was sucessfully uploaded and is visible under https://synocommunity.com/package/sabnzbd
direct link to download https://packages.synocommunity.com/sabnzbd/61/sabnzbd.v61.f42661%5Bevansport%5D.spk

**Comment by Safihre** [comment]
Strange, all builds failed with timeouts..
