### ISSUE TITLE
Packages server down

### ISSUE THREAD

**Issue by paulirish** [SynoCommunity/spkrepo#104]
repro url: https://packages.synocommunity.com/homeassistant/20/homeassistant.v20.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=r1000&build=64570

> # Error 503 first byte timeout
> first byte timeout

> ### Error 54113
> Details: cache-pao-kpao1770069-PAO 1689102944 418037530

> Varnish cache server

**Comment by publicarray** [comment]
Hey @paulirish thanks for letting us know. The server is still running fine but for some reason is having a hard time delivering this file. Usually this is when it's overloaded

In the mean time you can  download the file from

https://synocommunity.com/package/homeassistant
Instead

I'll investigate later if there is anything we can do about it.

**Comment by publicarray** [comment]
![image](https://github.com/SynoCommunity/spkrepo/assets/5497998/de3b4eea-89d0-4c59-b0ac-2150e0b64aac)

I think part of the problem is that I believe all online Synology NASs just ask for updates (json) around the same time unfortunately and don't spread the load evenly. I raised a ticked once with them and never heard back or they did not understand.

**Comment by paulirish** [comment]
> In the mean time you can download the file from
> [synocommunity.com/package/homeassistant](https://synocommunity.com/package/homeassistant) Instead

it's fine now but.... isnt it the same asset URL regardless? I got this 503 when clicking from that website.. but also noticed that my NAS was pulling from the same URL.


> I think part of the problem is that I believe all online Synology NASs just ask for updates (json) around the same time unfortunately and don't spread the load evenly.

Bummer.. Relatedly I'm slightly miffed that within the DSM, all scheduled tasks default to midnight. I know some variability in the cron times would spread the load for whatever. :) cheers

**Comment by publicarray** [comment]
Hi @Diaoul,
Do you know why we use use the additional query parameters when downloading a file `?arch=r1000&build=64570`?  do we need them? If they are not used I can filter them out on Fastly's end and increase the hit ratio. Every time Synology updates their build number the Fastly cache is effectively reset.

**Comment by Diaoul** [comment]
I just rebooted the server, let's see if it helps :grimacing:

**Comment by TimKras** [comment]
Not fixed, i'm getting this error for all downloads here: https://synocommunity.com/package/git

```
Error 503 Backend unavailable, connection timeout
Backend unavailable, connection timeout

Error 54113
Details: cache-dub4321-DUB 1689577272 1343005206

Varnish cache server
```

**Comment by publicarray** [comment]
> I just rebooted the server, let's see if it helps grimacing

Hm, I just logged on and our docker containers weren't running.. I've started them now

**Comment by TimKras** [comment]
I can confirm it is working again.
Thanks!

**Comment by PHENOMICAL** [comment]
> > I just rebooted the server, let's see if it helps grimacing
> 
> Hm, I just logged on and our docker containers weren't running.. I've started them now

Thank you. Also can confirm that it's working.
