### ISSUE TITLE
Existing users won't have a fs_uniquifier

### ISSUE THREAD

**Issue by publicarray** [SynoCommunity/spkrepo#109]
https://github.com/SynoCommunity/spkrepo/blob/8a5521ec16d7bd7595da3dcc9cf10fa00ca1ecdd/migrations/versions/76d559b4e873_add_fs_uniquifier.py#L17-L20

We need to generate them for exising users for the migration to work in production

**Comment by publicarray** [comment]
@mreid-tt I'll have a go at implemnting this but if you like you can have a look as well

**Comment by mreid-tt** [comment]
> @mreid-tt I'll have a go at implemnting this but if you like you can have a look as well

What would be the approach here? Would this be a database migration script or some other strategy?

**Comment by publicarray** [comment]
Just in the migration itself probably. Im making some progress with alembic

**Comment by hgy59** [comment]
This must be done by the migration when adding the not nullable field `fs_uniquifier`.

[Alembic: IntegrityError: "column contains null values" when adding non-nullable column](https://stackoverflow.com/questions/33705697/alembic-integrityerror-column-contains-null-values-when-adding-non-nullable) might give some hints.

**Comment by publicarray** [comment]
I can try the `server_default=''` but we need unique values for each user, not sure if that will do that. Instead this what I have so far:

```
    op.add_column(
        "user", sa.Column("fs_uniquifier", sa.String(length=255), nullable=True)
    )

    # Temporary table view
    t_users = sa.Table(
        "user",
        sa.MetaData(),
        sa.Column("id", sa.Integer()),
        sa.Column("fs_uniquifier", sa.Unicode(length=255)),
    )

    # Get all users
    connection = op.get_bind()
    results = connection.execute(
        sa.select(
            [
                t_users.c.id,
            ]
        )
    ).fetchall()

    # Interate over users
    for id_, in results:
        fs_uniquifier = hashlib.md5(os.urandom(32)).hexdigest()
        # Update the new columns.
        connection.execute(
            t_users.update()
            .where(t_users.c.id == id_)
            .values(fs_uniquifier=fs_uniquifier)
        )
    
    op.alter_column("user", "fs_uniquifier", nullable=False)
    op.create_unique_constraint(None, "user", ["fs_uniquifier"])
```

**Comment by hgy59** [comment]
I was hoping that we can call a function for `server_default`...

**Comment by hgy59** [comment]
It is probably fixed in https://github.com/sqlalchemy/alembic/issues/641
So it is worth a try...

**Comment by mreid-tt** [comment]
> I was hoping that we can call a function for `server_default`...

We may be able to. The challenge I am seeing others mention is that the `server_default` expects something than can be converted to SQL. I am seeing this sql function for md5 which may fit the requirement. See output from the PostgreSQL server in my test environment:

```
spkrepo=> select md5(random()::text);
               md5                
----------------------------------
 03c50904b3071ac130d078a40b912ec3
(1 row)
```

So we may be able to set that like this:

```
server_default=text("select md5(random()::text)")
```

**Comment by hgy59** [comment]
@publicarray I can't downgrade the db to the revision without fs_uniquifier.
probably the migration step is not yet reversible.

```
flask db downgrade d429595e8362

...
sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT for constraint UniqueConstraint(); it has no name
```

**Comment by publicarray** [comment]
> server_default=text("select md5(random()::text)")

Thanks I think this worked: `server_default=sa.text("md5(random()::text)")`

**Comment by mreid-tt** [comment]
> @publicarray I can't downgrade the db to the revision without fs_uniquifier.
> probably the migration step is not yet reversible.

Good catch @hgy59, from what I've seen we need to name the constraint on creation so that we can use that name when dropping it.

Essentially, we need to change:

https://github.com/SynoCommunity/spkrepo/blob/8a5521ec16d7bd7595da3dcc9cf10fa00ca1ecdd/migrations/versions/76d559b4e873_add_fs_uniquifier.py#L20

to

```
    op.create_unique_constraint("user_fs_uniquifier_const", "user", ["fs_uniquifier"])
```

and

https://github.com/SynoCommunity/spkrepo/blob/8a5521ec16d7bd7595da3dcc9cf10fa00ca1ecdd/migrations/versions/76d559b4e873_add_fs_uniquifier.py#L26

to

```
    op.drop_constraint("user_fs_uniquifier_const", "user", type_="unique")
```

We can choose any name once it makes sense and is unique.

**Comment by hgy59** [comment]
to fix the migration, the `76d559b4e873_add_fs_uniquifier.py` script has to use the name `"user_fs_uniquifier_key"` as first parameter of 
`op.create_unique_constraint("user_fs_uniquifier_key", "user", ["fs_uniquifier"])`
and
`op.drop_constraint("user_fs_uniquifier_key", "user", type_="unique")`

**Comment by hgy59** [comment]
@mreid-tt `"user_fs_uniquifier_key"` is the name that was created by default, so I propose to use this.

**Comment by publicarray** [comment]
The new version is up and running! :tada: 
Thanks for all your help
