### ISSUE TITLE
Members Link in SynoCommunity Website Footer Is Bad

### ISSUE THREAD

**Issue by war59312** [SynoCommunity/spkrepo#116]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### What happened?

The link "Maintained by [SynoCommunity](https://github.com/SynoCommunity?tab=members)" at the bottom of https://synocommunity.com/ , in the footer is bad.

Should point to https://github.com/orgs/SynoCommunity/people

Also, all the "View details links under "Easy Install", "Bleeding Edge", and "Open Source" just link to itself and seem pointless, gives no further details, recommend removing the links or truly give more info.

### Reproduction steps

n/a

**Comment by mreid-tt** [comment]
@war59312, this issue will be resolved in the `spkrepo` which is the code that generates the website so I've transferred your issue there.

**Comment by mreid-tt** [comment]
@war59312, the links you mention under the large icons take the user further down the page to where the content is. Given that the webpage is small, on a large screen it may appear to do nothing but on smaller screens it does work. Will consider if there is a need for a change there or not.
