### ISSUE TITLE
Package shown in page while not yet active

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spkrepo#127]
I've noticed this since quite a while, package are being showned on the page prior from being activated after the upload.

Would be nice to block that so things can be activated + delivered in bulk, mostly for dependent packages.

**Comment by hgy59** [comment]
> I've noticed this since quite a while, package are being showned on the page prior from being activated after the upload.
> 
> Would be nice to block that so things can be activated + delivered in bulk, mostly for dependent packages.

It is by intention that inactive packages are shown. This was introduced with  #111.
Inactive packages are for manual download only and do not appear in DSM Package Center.

**Comment by th0ma7** [comment]
I had no idea of that, thnx.  Still would be great to mark them as inactive on the per app page.

**Comment by hgy59** [comment]
> I had no idea of that, thnx. Still would be great to mark them as inactive on the per app page.

Yes this was done by #111. Inactive packages are shown with grey labels and the tooltip telling so, active packages have green labels...

**Comment by th0ma7** [comment]
Thnx!
