### ISSUE TITLE
Provide download link for each package, version, architecture

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spkrepo#13]
I would like to extend user interface so that user can gain access to packages:
- when system cannot connect to repository (SRM, offline system)
- when downgrade is required (troubles with dependency, publication mistake)
- when DSM 5.2 and DSM 6.x versions co-exists

**Comment by Safihre** [comment]
❤️

**Comment by publicarray** [comment]
I think this can be closed.

**Comment by ymartin59** [comment]
I am still not satisfied with current output. I would like to group architecture builds and display system name and version: "SRM 1.1" or "DSM 5.2", "DSM 6.1"...
