### ISSUE TITLE
Syncthing missing

### ISSUE THREAD

**Issue by CUCO-Ultimate** [SynoCommunity/spkrepo#18]
I have a Xpenology box, build by myself.

I added the feed to my DSM. I cannot find Syncthing as a package there.

Model Name: DS3617xs
Current DSM Version: DSM 6.1.7-15284

**Comment by ymartin59** [comment]
Not the right place. Please submit at https://github.com/SynoCommunity/spksrc/issues

**Comment by CUCO-Ultimate** [comment]
Did it https://github.com/SynoCommunity/spksrc/issues/3366

thx
