### ISSUE TITLE
Installation help?

### ISSUE THREAD

**Issue by DKeppi** [SynoCommunity/spkrepo#2]
Hello Diaoul,

i tried to install it on a Debian VM but i got a lot of errors when i want to create the db.
I fixed a lot with extra installing debian-packages or python-modules but now i stuck on following error:

./spkrepo/tests/testutils.py
from unittest.mock import Mock
ImportError: no module named mock

Which OS would be best to install?

**Comment by Diaoul** [comment]
I run spkrepo with python3 in production. Any python > 3.3 should work.

Integration and documentation are still on the to-do but I don't have much
time available.

**Comment by neutron666** [comment]
Same for me, got it up and running until the point i want to create the db. I also had to install many different packages (which aren't mentioned nowhere) but now, if i want to create the db i get:

sqlalchemy.exc.CompileError: The 'sqlite' dialect with current database version settings does not support in-place multirow inserts.

Also i had to create the data directory by hand and create a empty sqlite file, else there were more errors.

**Comment by DKeppi** [comment]
Ok, thank you - i will try it again with python3.
Think it was python2.7 installed

An How_To would be nice - only a litte one, not all the details!

**Comment by neutron666** [comment]
I used python 3.4, still no go..
