### ISSUE TITLE
Feature request: dnscrypt-proxy 2

### ISSUE THREAD

**Issue by raulsiles** [SynoCommunity/spkrepo#21]
Do you know if a dnscrypt-proxy 2 (v2) package is available for Synology DSM, or if someone is working on it? 

I'm aware there is a dnscrypt-proxy (v1) beta package in the SynoCommunity repository, but it is not version 2 (with adds support for the recent protocols, such as DNSCrypt v2 and DNS-over-HTTPS).

**Comment by ymartin59** [comment]
Not the right repository to report. Work is in progress: https://github.com/SynoCommunity/spksrc/pulls?q=is%3Apr+dnscrypt-proxy+is%3Aclosed
It should be available in Package Center soon https://synocommunity.com/
