### ISSUE TITLE
mosquitto on RS816

### ISSUE THREAD

**Issue by hmueller01** [SynoCommunity/spkrepo#25]
The latest mosquitto package for an Armada 385 88F6820 CPU is 1.4.9-5. This version will not start on DSM 6.2 (service can not be started). Can you please provide v1.4.14-9 for this architecture? Log says that it uses DSM 5+6 generic service. So my hope is that it will work on my DSM 6.2.

Thanks.

**Comment by ymartin59** [comment]
Not the right place to notify this. It should be at https://github.com/SynoCommunity/spksrc/issues
By the way, I published lacking package.

**Comment by hmueller01** [comment]
Sorry for posting at the wrong place. Thanks for the package anyway. The new version starts. First test worked too. Thanks a lot!!!
