### ISSUE TITLE
NZBget doesn not work on NAS

### ISSUE THREAD

**Issue by tariqghazi** [SynoCommunity/spkrepo#29]
hello,

I have a Synology NAS ds218+ and a few weeks ago NZBGet stopped working.
I had the login url bookmarked but all of sudden it didnt work anymore. I asked support to help me out but they wont deliver support to 3rd party packagaes.

The package is still installed on my NAS but somehow i dont know how to get the login url or get it to work. Can someone help me out?

Tariq

**Comment by ymartin59** [comment]
Sorry. Not the right place to report such issue. Please submit at https://github.com/SynoCommunity/spksrc/issues
