### ISSUE TITLE
Mono aarch64 update 5.18.0.240-12 causing SecureChannelFailure in Sonarr/Radarr

### ISSUE THREAD

**Issue by mph8er** [SynoCommunity/spkrepo#31]
I have two Synology units; one DS418 and a DS1817+. DS418 is arm64 v8 based while my DS1817+ is Atom-based. Recently, I updated mono on both from 5.18.0.240 to 5.18.0.240-12. On the arm64 system, I'm getting the message at the bottom of the radarr.log file when trying to do a test connection to a newsgroup indexer. 

I uninstalled, then cleaned up the folders and files left behind, then I ran through a clean install of mono, sonarr and radarr and am still encountering the issue. Each Synology runs a different API key and both work on the 1817+ and both fail on the 418. Googling seemed to indicate this happened a couple years ago in mono, but considering the version is newer, I was curious if the cross-compile process could've caused it to crop up again? I was unable to find anywhere to download previous versions to confirm that is the issue. Any chance to get some of the previous versions to confirm if this is an issue? 5.18.0.240 was the version I'd been on since December or so before upgrading to -12. Let me know what logs you need.
[radarr.log](https://github.com/SynoCommunity/spkrepo/files/3006168/radarr.log)

Also, when I went to update, I noticed the package pictures on the repo appear to be wrong. Again, this is only occurring on the SynoCommunity repo on the 418 (assuming these are running on different repos). I removed the repo and readded it figuring it might be a cache issue, but that didn't resolve the issue either. It looks fine from the main Community page, but once I click on an item, the icons are wrong. Notice the php icon showing up for the Radarr installer.
[repo without issue](https://user-images.githubusercontent.com/22526473/54966195-8a1aee00-4f41-11e9-8cf4-2b65495e3749.png)
[repo image issue](https://user-images.githubusercontent.com/22526473/54966194-8a1aee00-4f41-11e9-8cd0-a46a11694059.png)

**Comment by ymartin59** [comment]
Hello. Sorry, not the right project to report such issue. Please follow https://github.com/SynoCommunity/spksrc/issues/3666
