### ISSUE TITLE
Cannot install packages as they are not provided by Synology

### ISSUE THREAD

**Issue by UweZiegenhagen** [SynoCommunity/spkrepo#32]
I have successfully added the synocommunity package repository on my DS214+ running DSM 6.2.1-23824 Update 6 however when I try to install e.g. nano or mc I get an error message stating that the package could not be installed as it has not been provided by Synology.

![syno](https://user-images.githubusercontent.com/1240092/55669055-219e0c00-5873-11e9-8264-c74140792f52.png)

What am I doing wrong?

**Comment by kekukui** [comment]
![image](https://user-images.githubusercontent.com/20834957/56157610-e8118300-5f8d-11e9-980c-f1416b911915.png)

**Comment by UweZiegenhagen** [comment]
That did the trick, thank you!
