### ISSUE TITLE
[package request] WebGrab Plus

### ISSUE THREAD

**Issue by kekukui** [SynoCommunity/spkrepo#33]
Can someone please add a '**WebGrab Plus**' package here (to streamline installation for **TVheadend** users)

**WebGrab Plus manual setup instructions**
http://www.webgrabplus.com/documentation/installation/synology-nas
http://www.webgrabplus.com/node/22
http://webgrabplus.com/documentation/interact-your-pvr-software/tvheadend

**Comment by ymartin59** [comment]
Hello. Not the right project to submit such request. Work is in progress, please follow https://github.com/SynoCommunity/spksrc/pull/3639
