### ISSUE TITLE
unable to download roundcube

### ISSUE THREAD

**Issue by andrea2gts** [SynoCommunity/spkrepo#35]
no roundcube package

**Comment by CyberBlaed** [comment]
Try to grab them from the website directly, the repo seems to be down and I don't know why.
(I just use the website directly and manually install the package)

https://synocommunity.com/package/roundcube

**Comment by ymartin59** [comment]
Not the right place for such a request. Please submit at: https://github.com/SynoCommunity/spksrc/issues
