### ISSUE TITLE
Problem executing/installing FlexGet

### ISSUE THREAD

**Issue by JHSNL** [SynoCommunity/spkrepo#42]
Hi,

don't know if the problem is with you guys but I am trying to install FlexGet but getting the message that it can't execute the package. I have some experience with computers but I have no clue how to fix this issue.

Can anybody help me with this? I am running DSM 6.2.2-24922 Update 4 

Thnx in advance!

**Comment by Diaoul** [comment]
Wrong place, head to https://github.com/SynoCommunity/spksrc
