### ISSUE TITLE
Alphabetical sorting of architectures

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spkrepo#5]
Currently, the order of architectures on the package view looks like this for `deluge`:
`armadaxp x86 bromolow cedarview avoton evansport armada370 88f628x armada375 comcerto2k alpine alpine4k`

This is based on creation date/upload order, if I'm not mistaken. For a more consistent look, it would seem better to sort alphabetically instead.

**Comment by ymartin59** [comment]
Good idea. Implemented in #46
