### ISSUE TITLE
Sickbeard failing all TVDB searches after update

### ISSUE THREAD

**Issue by gramster** [SynoCommunity/spkrepo#51]
Not sure if this is the right place to file this, but I updated Sickbeard Custom via the Syno Package Manager and now all the TVDB searches fail. I tried uninstalling and reinstalling Sickbeard but still have an issue (and now all my existing shows are gone because Sickbeard can't seem to add them back without TVDB).

It's possible its just TVDB being down, as the logs show:

2020-08-08 15:04:45 SHOWQUEUE-ADD :: Error contacting TVDB: Could not connect to server: 

But I checked their forums and see no mention of this.

**Comment by Safihre** [comment]
You need to report it at SynoCommunity/spksrc 👍

**Comment by gramster** [comment]
Closing; filing elsewhere.
