### ISSUE TITLE
Allow longer firmware version number

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spkrepo#52]
At the moment, DSM firmware version is limited to 3 characters length "A.B", so it is not possible to publish specific package targeting minor version like 6.2.2

**Comment by ymartin59** [comment]
@th0ma7 May you please confirm you still need (or not) this version support change?

**Comment by th0ma7** [comment]
confirmed, not needed anymore as using `A.B-build` independently of the `C` in `A.B.C-build`

**Comment by th0ma7** [comment]
This can be closed.
