### ISSUE TITLE
DSM 7.0 Preview Support

### ISSUE THREAD

**Issue by baya44** [SynoCommunity/spkrepo#55]
Hello,

I'm actually testing DSM 7.0 on my DS1817+ and i have some packages who don't work because privilege issues.
Synology give this link for dev: https://help.synology.com/developer-guide/privilege/preface.html
The list of package: git, python, python3, plexpy custom, sickbeard-custom, ffmpeg and Gateone.

**Comment by ymartin59** [comment]
Refer to #4170
