### ISSUE TITLE
How to install on DSM 6

### ISSUE THREAD

**Issue by dragonslore** [SynoCommunity/spkrepo#56]
Hello,

Sickchill team redirected me to your repository for a fresh Sickchill install on my Syno as regular Sickbeard package is not working anymore for me.
I didn't find a proper way to install it, can you please help me ?

Thanks in advance for your help
Manu

**Comment by Safihre** [comment]
You should go to SynoCommunity/spksrc.

**Comment by dragonslore** [comment]
This is what I did but i don't see any pkg to download...only raw sources.

**Comment by Safihre** [comment]
No, I mean you should report this here: https://github.com/SynoCommunity/spksrc/issues

**Comment by dragonslore** [comment]
Ok thank you :)
