### ISSUE TITLE
Update Radarr to Aphrodite branch

### ISSUE THREAD

**Issue by Casuallynoted** [SynoCommunity/spkrepo#59]
Hello,

At the moment I am using Radarr in a docker container rather than the Syno repo one (which I'd prefer to use). Part of the reason for it is because the syno repo one is tied to the "develop" branch, which contains the older version of Radarr without the new UI. While that wouldn't normally be an issue, that version of Radarr does not include the ability to restore from a backup. When I initially moved over to my Syno machine, I realised if I used the synocommunity repo version I'd have to give up on my backup and not have all the content already indexed. Is there a way the community repo version could be updated to the Aphrodite branch so that it supports restoring from a backup?

**Comment by Safihre** [comment]
Please report at: https://github.com/SynoCommunity/spksrc

**Comment by Safihre** [comment]
@ymartin59 Maybe we should set an GitHub Issue Template for this repository that has a big warning that this repository is not for the packages?
Or maybe even make this repo private?

**Comment by Casuallynoted** [comment]
Oh gosh, I apologize!
