### ISSUE TITLE
Deluge 2.0.3-12 fails to load Autoadd plugin.

### ISSUE THREAD

**Issue by MrRalphMan** [SynoCommunity/spkrepo#60]
Hi, 

When I attempt to activate the autoAdd plugin within Deluge running on my Synology DS215j, I get the following failure in the log.

`Traceback: <type 'exceptions.ValueError'>: No JSON object could be decoded
/volume1/@appstore/python/lib/python2.7/site-packages/twisted/internet/defer.py:151:maybeDeferred
/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/plugins/init.py:27:enable
build/bdist.linux-armv7l/egg/deluge_autoadd/core.py:88:enable
/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/config.py:468:save
/var/packages/python/target/lib/python2.7/json/__init__.py:339:loads
/var/packages/python/target/lib/python2.7/json/decoder.py:364:decode
/var/packages/python/target/lib/python2.7/json/decoder.py:382:raw_decode

20:57:18 [WARNING ][deluge.pluginmanagerbase      :246 ] Problems occured disabling plugin: AutoAdd
`

This was working previously and I'm not 100% sure what caused it to fail.

Version of the Plugin is AutoAdd-1.8-py2.7.egg, according to the Plugin folder.  Is there anything I can do to remediate this?

Many Thanks,

Paul

**Comment by Diaoul** [comment]
Please report the issue here: https://github.com/SynoCommunity/spksrc/
