### ISSUE TITLE
synocli-disk davfs2 setup

### ISSUE THREAD

**Issue by firebladeRR1k** [SynoCommunity/spkrepo#66]
I am new to davfs2 and am having issues using the synocli-disk implementation of it.  I am thinking there may be missing steps or configuration for it.  I think the mount command is not finding the mount.davfs file (sym link) in /usr/local/sbin/.  Running "mount -t davfs https://serverofwebdav.com/ /volume1/locationOfMount/ -o noexec" generates an error of "mount: unknown filesystem type davfs".  I added a sym link in /sbin/ to mount.davfs and unmount.davfs and it gets a bit further.  It then gives an error of "sbin/mount.davfs: group davfs2 does not exist".

Should the installer have set up these up to work with mount and set up users/groups?  Also, I do not see a .conf file set up for davfs2.

I have tried this as a regular user sudo'd and also as root. Same results.

Thanks for any help or direction that can be provided.

**Comment by firebladeRR1k** [comment]
not sure I posted this in the correct location

**Comment by Diaoul** [comment]
Indeed, please post an issue here: https://github.com/SynoCommunity/spksrc although TBH, I am not sure someone will be able to answer this very specific question.
