### ISSUE TITLE
DSM7 strips out all packages marked as beta

### ISSUE THREAD

**Issue by picrap** [SynoCommunity/spkrepo#77]
Hi SynoCommunity,

it took me a while to figure out this one, but it seems that DSM7 simply hides any third party package marked as beta (regardless the fact that beta option was checked). It now only shows beta from its own source.
Did you notice this?

**Comment by hgy59** [comment]
I noticed this. So you have to manually download beta packages for DSM 7 (but the manual download is currently not available).

**Comment by Diaoul** [comment]
Downloads seems to be available now.
