### ISSUE TITLE
Support for 88F6702 architecture 

### ISSUE THREAD

**Issue by picrap** [SynoCommunity/spkrepo#80]
Hi,

I recently bought a (very old) DS112j (at a very low price 😁), whose architecture is MARVELL Kirkwood 88F6702.
I can’t add SynoCommunity as package source (https://packages.synocommunity.com). Since it works on my other NAS, I guess it is just an unsupported platform.
I downloaded and manually installed a package for 88f628x (Mono) and it worked, so I suppose 88F6702 can be assimilated as 88F628x.

Thanks.

**Comment by hgy59** [comment]
@picrap You model is already supported. The arch for manual download is `88f6281` (see https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures)
<html><body>

<html><body>


System Model | CPU Model | Synology Package Arch | SynoCommunity Arch | Generic Arch
-- | -- | -- | -- | --
DS112j | Marvell Kirkwood 88F6702 | 88f628x | 88f6281 | armv5


</body>
</html>

**Comment by picrap** [comment]
It works today, thank you.
