### ISSUE TITLE
publish does not work anymore

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spkrepo#81]
Wanted to publish `znc 1.8.2-19` to the repo, but get the error message about conflictiong architectures:

```
 make publish-arch-aarch64-6.1
 ...
 {"message": "Conflicting architectures: aarch64, armada37xx, rtd1296"}
```

This might be caused by the latests repo update?

The publish (minio `2021.09.18-9`) did work on `2021-09-21 19:46`.

**Comment by Diaoul** [comment]
This is strange, I did not modify any code that could've caused this. There's no record of rev 19 of the package in the repo.

**Comment by hgy59** [comment]
It must be a generic error, as incrementing SPK_REV = 20 gives the same error `Conflicting architectures: ...`.

**Comment by hgy59** [comment]
oops, in the INFO file is still
```
version="1.8.2-18"
```

will have to analyze this...

**Comment by hgy59** [comment]
a full rebuild fixed this.
