### ISSUE TITLE
 Increase MAX_CONTENT_LENGTH

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spkrepo#82]
last increase was for Mono in #30.
I am about to release .NET 6 SDK packages where the packages for x64 are about 180MB.

Please increate MAX_CONTENT_LENGTH to ~ 200MB.

**Comment by ymartin59** [comment]
From my point of view, application package only need "runtime" components on DSM... does it make sense to have complete SDK (compiler, headers... but just a guess of mine) included in package?

**Comment by th0ma7** [comment]
Hopefully before long if Synology releases DSM7 kernels we could take another look at building ourselves updated compilers and then use them to build mono and rustc for instance...  Other than that, how are we in terms of space online?

**Comment by hgy59** [comment]
> From my point of view, application package only need "runtime" components on DSM... does it make sense to have complete SDK (compiler, headers... but just a guess of mine) included in package?

If we ever want to have the SDK, I thought it is better to bundle runtime and SDK - otherwise there will be conflicts with dedicated packages (only one `dotnet` command in the path...).

.net is a great playground and we have other packages with compilers (or interpreters) like mono, python, ruby, erlang, nodejs, lua, ...
And maybe some day we have synocli-develop with gcc, build-tools, etc.

But I have no problem to release a package with dotnet runtime only.
May be the `**arr` packages can benefit of it.

**Comment by Diaoul** [comment]
I've done the change. `MAX_CONTENT_LENGTH = 200 * 1024 * 1024` for Flask and `client_max_body_size` is already 200MB for NGINX.
