### ISSUE TITLE
cannot import name 'MigrateCommand' from 'flask_migrate'

### ISSUE THREAD

**Issue by Flachdachs** [SynoCommunity/spkrepo#88]
Following the instructions of the README.md I get an error in step "3. Create the tables with python manage.py db create"

```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from flask_migrate import MigrateCommand
ImportError: cannot import name 'MigrateCommand' from 'flask_migrate' (/home/user/.cache/pypoetry/virtualenvs/spkrepo-vBTx5oS9-py3.7/lib/python3.7/site-packages/flask_migrate/__init__.py)
```

Doing a little bit of research I found https://stackoverflow.com/questions/68527489/cant-import-migratecommand-from-flask-migrate telling that Flask-Script is no longer supported. See also: https://github.com/miguelgrinberg/Flask-Migrate/issues/407

**Comment by publicarray** [comment]
Fixed in 4640a220dfaef507d05f1ea89065c8c94a9c81ba
